name: SlipNote
options:
  bundleIdPrefix: com.slipnote
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    MARKETING_VERSION: "1.0.5"
    CURRENT_PROJECT_VERSION: "6"
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "14.0"

packages:
  GRDB:
    url: https://github.com/groue/GRDB.swift
    from: "6.24.0"
  HotKey:
    url: https://github.com/soffes/HotKey
    from: "0.2.0"

targets:
  SlipNote:
    type: application
    platform: macOS
    sources:
      - path: SlipNote
        excludes:
          - "**/*.entitlements"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.slipnote.app
        INFOPLIST_FILE: SlipNote/Info.plist
        CODE_SIGN_ENTITLEMENTS: SlipNote/SlipNote.entitlements
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/../Frameworks"
        ENABLE_HARDENED_RUNTIME: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    dependencies:
      - package: GRDB
      - package: HotKey
    entitlements:
      path: SlipNote/SlipNote.entitlements

schemes:
  SlipNote:
    build:
      targets:
        SlipNote: all
    run:
      config: Debug
    profile:
      config: Release
    archive:
      config: Release
